### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by net-tech** [sawa-ko/revoltx#177]
Hi there,

I'm having a bit of a strange issue. When I try to start my bot, I get the following error message

```js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/net-tech-/Developer/kydzs-splatoon-revolt-temp/node_modules/@kaname-png/revoltx/dist/lib/preconditions/conditions' imported from /Users/net-tech-/Developer/kydzs-splatoon-revolt-temp/node_modules/@kaname-png/revoltx/dist/index.js
```

I have checked manually, and the file does exist in node modules. I've tried reinstalling, deleting all node modules, using different  package managers, and etc. While I know this may not be entirely the library's fault, I wanted to ask if you had any idea of what might be causing the issue.

Node Version `20.4.0`
Typescript version `5.1.6`
Revoltx version `2.0.5`

**Comment by sawa-ko** [comment]
![image](https://github.com/sawa-ko/revoltx/assets/56084970/19b98624-7dae-43c8-b655-0c3f89512710)

Strange, the file does exist in the production build in npmjs. Are you using commonjs or esm?

**Comment by net-tech** [comment]
@sawa-ko Yeah, so I am using ESM. I can see the files in node modules. When I go to the file that imports everything in revoltx, `dist/index.js`, the errors seem to get more specific:
```js
Could not find a declaration file for module '. /lib/preconditions/conditions'. '/Users/net-tech-/Developer/kydzs-splatoon-
revolt-temp/node_modules/@kaname-png/revolt×/dist/lib/preconditions/conditions.js' implicitly has an 'any' type. ts (7016)
```
and the same error appears for every `export * from "somePath"` in the revoltx `index.js` file.

Here's my TSConfig:

```json
{
	"compilerOptions": {
		"module": "ESNext",
		"moduleResolution": "Node",
		"target": "ESNext",
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"strict": true,
		"skipLibCheck": true,
		"allowJs": false,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"allowSyntheticDefaultImports": true,
		"noImplicitAny": true,
		"noImplicitThis": true,
		"noFallthroughCasesInSwitch": true,
		"noImplicitOverride": true,
		"pretty": true,
		"rootDir": "./src",
		"outDir": "./dist",
		"experimentalDecorators": true
	}
}
```

**Comment by net-tech** [comment]
The issue resolved itself after a full reinstall.
